// <auto-generated />
using System;
using IdentityServer4.DataAccess;
using IdentityServer4_SPA_Client.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityServer4.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.DataModels.Security.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("IdentityServer4.DataModels.Shared.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("IdentityServer4.DataModels.Shared.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 33,
                            Abbreviation = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 34,
                            Abbreviation = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 35,
                            Abbreviation = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 36,
                            Abbreviation = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 37,
                            Abbreviation = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 38,
                            Abbreviation = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 39,
                            Abbreviation = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 40,
                            Abbreviation = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 41,
                            Abbreviation = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 42,
                            Abbreviation = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 43,
                            Abbreviation = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 44,
                            Abbreviation = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 45,
                            Abbreviation = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 46,
                            Abbreviation = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 47,
                            Abbreviation = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 48,
                            Abbreviation = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 49,
                            Abbreviation = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 50,
                            Abbreviation = "CD",
                            Name = "Congo, the Democratic Republic of the"
                        },
                        new
                        {
                            Id = 51,
                            Abbreviation = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 52,
                            Abbreviation = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 53,
                            Abbreviation = "CI",
                            Name = "Cote D'Ivoire"
                        },
                        new
                        {
                            Id = 54,
                            Abbreviation = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 55,
                            Abbreviation = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 56,
                            Abbreviation = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 57,
                            Abbreviation = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 58,
                            Abbreviation = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 59,
                            Abbreviation = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 60,
                            Abbreviation = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 61,
                            Abbreviation = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 62,
                            Abbreviation = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 63,
                            Abbreviation = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 64,
                            Abbreviation = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 65,
                            Abbreviation = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 66,
                            Abbreviation = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 67,
                            Abbreviation = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 68,
                            Abbreviation = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 69,
                            Abbreviation = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 70,
                            Abbreviation = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 71,
                            Abbreviation = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 72,
                            Abbreviation = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 73,
                            Abbreviation = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 74,
                            Abbreviation = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 75,
                            Abbreviation = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 76,
                            Abbreviation = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 77,
                            Abbreviation = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 78,
                            Abbreviation = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 79,
                            Abbreviation = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 80,
                            Abbreviation = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 81,
                            Abbreviation = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 82,
                            Abbreviation = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 83,
                            Abbreviation = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 84,
                            Abbreviation = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 85,
                            Abbreviation = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 86,
                            Abbreviation = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 87,
                            Abbreviation = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 88,
                            Abbreviation = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 89,
                            Abbreviation = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 90,
                            Abbreviation = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 91,
                            Abbreviation = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 92,
                            Abbreviation = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 93,
                            Abbreviation = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            Id = 94,
                            Abbreviation = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 95,
                            Abbreviation = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 96,
                            Abbreviation = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 97,
                            Abbreviation = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 98,
                            Abbreviation = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 99,
                            Abbreviation = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 100,
                            Abbreviation = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 101,
                            Abbreviation = "IR",
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            Id = 102,
                            Abbreviation = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 103,
                            Abbreviation = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 104,
                            Abbreviation = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 105,
                            Abbreviation = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 106,
                            Abbreviation = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 107,
                            Abbreviation = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 108,
                            Abbreviation = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 109,
                            Abbreviation = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 110,
                            Abbreviation = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 111,
                            Abbreviation = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 112,
                            Abbreviation = "KP",
                            Name = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            Id = 113,
                            Abbreviation = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 114,
                            Abbreviation = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 115,
                            Abbreviation = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 116,
                            Abbreviation = "LA",
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 117,
                            Abbreviation = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 118,
                            Abbreviation = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 119,
                            Abbreviation = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 120,
                            Abbreviation = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 121,
                            Abbreviation = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            Id = 122,
                            Abbreviation = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 123,
                            Abbreviation = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 124,
                            Abbreviation = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 125,
                            Abbreviation = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 126,
                            Abbreviation = "MK",
                            Name = "Macedonia, the Former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 127,
                            Abbreviation = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 128,
                            Abbreviation = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 129,
                            Abbreviation = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 130,
                            Abbreviation = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 131,
                            Abbreviation = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 132,
                            Abbreviation = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 133,
                            Abbreviation = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 134,
                            Abbreviation = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 135,
                            Abbreviation = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 136,
                            Abbreviation = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 137,
                            Abbreviation = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 138,
                            Abbreviation = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 139,
                            Abbreviation = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 140,
                            Abbreviation = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 141,
                            Abbreviation = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 142,
                            Abbreviation = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 143,
                            Abbreviation = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 144,
                            Abbreviation = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 145,
                            Abbreviation = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 146,
                            Abbreviation = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 147,
                            Abbreviation = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 148,
                            Abbreviation = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 149,
                            Abbreviation = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 150,
                            Abbreviation = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 151,
                            Abbreviation = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 152,
                            Abbreviation = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 153,
                            Abbreviation = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 154,
                            Abbreviation = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 155,
                            Abbreviation = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 156,
                            Abbreviation = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 157,
                            Abbreviation = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 158,
                            Abbreviation = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 159,
                            Abbreviation = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 160,
                            Abbreviation = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 161,
                            Abbreviation = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 162,
                            Abbreviation = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 163,
                            Abbreviation = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 164,
                            Abbreviation = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            Id = 165,
                            Abbreviation = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 166,
                            Abbreviation = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 167,
                            Abbreviation = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 168,
                            Abbreviation = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 169,
                            Abbreviation = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 170,
                            Abbreviation = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 171,
                            Abbreviation = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 172,
                            Abbreviation = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 173,
                            Abbreviation = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 174,
                            Abbreviation = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 175,
                            Abbreviation = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 176,
                            Abbreviation = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 177,
                            Abbreviation = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 178,
                            Abbreviation = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 179,
                            Abbreviation = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = 180,
                            Abbreviation = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 181,
                            Abbreviation = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 182,
                            Abbreviation = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 183,
                            Abbreviation = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 184,
                            Abbreviation = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 185,
                            Abbreviation = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 186,
                            Abbreviation = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 187,
                            Abbreviation = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 188,
                            Abbreviation = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 189,
                            Abbreviation = "CS",
                            Name = "Serbia and Montenegro"
                        },
                        new
                        {
                            Id = 190,
                            Abbreviation = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 191,
                            Abbreviation = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 192,
                            Abbreviation = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 193,
                            Abbreviation = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 194,
                            Abbreviation = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 195,
                            Abbreviation = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 196,
                            Abbreviation = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 197,
                            Abbreviation = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 198,
                            Abbreviation = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 199,
                            Abbreviation = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 200,
                            Abbreviation = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 201,
                            Abbreviation = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 202,
                            Abbreviation = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 203,
                            Abbreviation = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 204,
                            Abbreviation = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 205,
                            Abbreviation = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 206,
                            Abbreviation = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 207,
                            Abbreviation = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 208,
                            Abbreviation = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            Id = 209,
                            Abbreviation = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 210,
                            Abbreviation = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 211,
                            Abbreviation = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 212,
                            Abbreviation = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 213,
                            Abbreviation = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 214,
                            Abbreviation = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 215,
                            Abbreviation = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 216,
                            Abbreviation = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 217,
                            Abbreviation = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 218,
                            Abbreviation = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 219,
                            Abbreviation = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 220,
                            Abbreviation = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 221,
                            Abbreviation = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 222,
                            Abbreviation = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 223,
                            Abbreviation = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 224,
                            Abbreviation = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 225,
                            Abbreviation = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 226,
                            Abbreviation = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 227,
                            Abbreviation = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 228,
                            Abbreviation = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 229,
                            Abbreviation = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 230,
                            Abbreviation = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 231,
                            Abbreviation = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 232,
                            Abbreviation = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 233,
                            Abbreviation = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 234,
                            Abbreviation = "VI",
                            Name = "Virgin Islands, US"
                        },
                        new
                        {
                            Id = 235,
                            Abbreviation = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 236,
                            Abbreviation = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 237,
                            Abbreviation = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 238,
                            Abbreviation = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 239,
                            Abbreviation = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("IdentityServer4.DataModels.Security.ApplicationUser", b =>
                {
                    b.HasOne("IdentityServer4.DataModels.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("IdentityServer4.DataModels.Shared.Address", b =>
                {
                    b.HasOne("IdentityServer4.DataModels.Shared.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IdentityServer4.DataModels.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IdentityServer4.DataModels.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityServer4.DataModels.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IdentityServer4.DataModels.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
